### ISSUE TITLE
Source in .NET Standard

### ISSUE THREAD

**Issue by FantasticFiasco** [edumentab/cqrs-starter-kit#9]
Would you find it beneficial to complement, or convert, the source from .NET Framework to .NET Standard?

I would happily provide you with a PR if you'd like.

**Comment by tndata** [comment]
At the moment it's not a priority for us to convert the package to .NET Standard, although its a nice idea.

**Comment by jchannon** [comment]
Just tried to open the solution on my mac and had errors and spotted this issue. Would get my upvote :)
